### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jkowalleck** [jkowalleck/cyclonedx-php-composer#2]
- [x] convert to psalm and fix all findings
- [ ] check all authors, add original author if not changed to much 
- [x] `declare(strict_types=1);` to all files
- [ ] set varnames lanegth to >= 3
- [ ] update help page in README.md
- [ ] split serializers to proper sub parts
- [ ] optional: make licenses unique in model -- canonicalize? 
- [ ] normalice in XML if defined so
- [x] implement packageUrl as in specs - see https://github.com/jkowalleck/packageurl-php
- [x] tools finalization - see  https://github.com/CycloneDX/cyclonedx-php-composer/pull/18#issuecomment-787047203
- [x] use `php -d` like https://github.com/jkowalleck/packageurl-php/blob/php_config/phpunit.php.ini

**Comment by jkowalleck** [comment]
was incorporated into https://github.com/CycloneDX/cyclonedx-php-composer/milestone/2
